### ISSUE TITLE
MTP and ADB still not working on latest UBPorts build

### ISSUE THREAD

**Issue by KJS1212** [Kethen/samsung-exynos8890#10]
I have enabled developer options and rebooted and adb still does not work. Running sudo adbd also doesn't work. MTP does not work and I have looked through every setting and booted my laptop into 2 linux distros and windows and still, MTP does not work. Please help

**Comment by Kethen** [comment]
duplicate of https://gitlab.com/ubports/porting/community-ports/android11/samsung-galaxy-s7/samsung-exynos8890/-/issues/12
