### ISSUE TITLE
OTA

### ISSUE THREAD

**Issue by mertcaners12** [Kethen/samsung-exynos8890#2]
upgrading to version 9 just reboots to recovery

**Comment by mertcaners12** [comment]
version doesnt matter it  just restarts to recovery

**Comment by Kethen** [comment]
twrp does not know how to handle ubuntu touch style ota
if you want to try the ota feature you'll have to switch to ubuntu touch recovery, you can find that on the 2022-07-23 release

**Comment by Kethen** [comment]
To make sure that ota would work, you should try out the ubuntu touch installer with this pending config, herolte for flat, hero2lte for edge
https://github.com/ubports/installer-configs/pull/197

You can run a custom config by using the -f flag with the installer
https://github.com/ubports/ubports-installer
