### ISSUE TITLE
No wifi is shown on setup

### ISSUE THREAD

**Issue by Master37373** [Kethen/samsung-exynos8890#3]
On the setup screen there is no wifi shown. I have to go through setup and disable wifi and enable again in order to see any wifi connections

**Comment by Kethen** [comment]
Should be working as of devel version 47 (2022-08-17/2), please verify if possible

**Comment by Master37373** [comment]
Works now, thank you so much

**Comment by Kethen** [comment]
@Master37373 thanks for testing
