### ISSUE TITLE
Android apps not working

### ISSUE THREAD

**Issue by Master37373** [Kethen/samsung-exynos8890#4]
I tried to install some android apps with anbox but as soon as i open any android app the app crashes and anbox starting to install the apps twice or more

**Comment by Kethen** [comment]
anbox seems to crash on multiple devices on dev channel at the moment

In the long term you'll probably have better luck with waiting for waydroid to support halium 11 ubuntu touch

**Comment by OPGL** [comment]
Will we be able to run android apps on this rom?

**Comment by Kethen** [comment]
As said, we’ll see when waydroid halium 11 support lands

**Comment by Kethen** [comment]
Anyway note that anbox is currently deprecated in ubuntu touch and is no longer receiving support

**Comment by Kethen** [comment]
for until official waydroid halium 11 images are out:
https://github.com/Kethen/waydroid_build/releases
