### ISSUE TITLE
MTP/ADB doesnt work

### ISSUE THREAD

**Issue by OPGL** [Kethen/samsung-exynos8890#5]
doesn't detects device, even when dev mode on

workaround: 
sudo adbd 
in terminal

**Comment by Master37373** [comment]
Works perfect for me

**Comment by Kethen** [comment]
mtp has been working for a very long while, even on the flashable zip builds

adb has been working since last friday, but only on the ubport installer/ota builds
https://forums.ubports.com/topic/8025/samsung-galaxy-s7-s7-edge-exynos-herolte-hero2lte-call-for-testing
