### ISSUE TITLE
Bootloop on V49 Dev Channel Update

### ISSUE THREAD

**Issue by Master37373** [Kethen/samsung-exynos8890#7]
After installing i was stuck on the S7 Logo it stayed for ever but nothing happened. After Hard reset it seems like it was booting, the black Lock screen was shown. But then it restarted and now its stuck on Ubuntu touch boot Animation

**Comment by Master37373** [comment]
After Factory reset the phone was booting on setup. Soft rebooted once. I could not connect to wifi, it showed wifis for a second than no wifi was shown and i had to select time zone. Something went wrong with the build.

**Comment by Master37373** [comment]
Same issue on v50

**Comment by Kethen** [comment]
> Same issue on v50

there is a change in the rootfs that causes issue with the patched pulse audio modules during the upgrade process, unity8 seems to not appreciate pulse audio dying, causing the logo stuck

To stop the bootlooping, do a full install with the ubports installer https://forums.ubports.com/topic/8025/samsung-galaxy-s7-s7-edge-exynos-herolte-hero2lte-call-for-testing, it will install v50 properly

Don't do OTA updates until this is resolved

**Comment by Master37373** [comment]
Will do when i get access to a pc again. Thank you

**Comment by Kethen** [comment]
Please note that version 51 has issues, the image server should refresh in ~7 hours
Avoid using the installer until then

**Comment by Master37373** [comment]
Hey, 
I could not figure out how to install it with the installer since the device is not supported by the installer currently. I could not find any guide how to install it with the configuration file on macOS.

**Comment by Master37373** [comment]
Nevermind i dont know how but i managed to get it working.
